# Generated by Django 4.0.4 on 2022-12-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_viewer',
            field=models.BooleanField(default=False, verbose_name='Normal User'),
        ),
    ]
