# Generated by Django 4.0.4 on 2023-01-02 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_is_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_viewer',
        ),
    ]
