# Generated by Django 4.0.4 on 2023-01-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_is_creator_remove_user_is_viewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
