# Generated by Django 4.0.4 on 2023-01-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='price',
            field=models.FloatField(blank=True, default=23.32, null=True),
        ),
    ]
