# Generated by Django 4.0.4 on 2023-01-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_channel_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='price',
            new_name='channel_price',
        ),
    ]
