# Generated by Django 4.0.4 on 2023-01-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_price_channel_channel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_price',
            field=models.FloatField(default=23.32),
        ),
    ]
