# Generated by Django 4.0.4 on 2023-01-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_channel_channel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
