# Generated by Django 4.0.4 on 2023-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_channel_channel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adip', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adip dolor sit amet dolore magna aliquet dolore magna aliquet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum d lorem ipsum dolor sit amet lorem ipsum d', max_length=700, null=True)),
                ('user_image_1', models.ImageField(blank=True, default='/static/1600x900.png', null=True, upload_to='about_images')),
                ('user_image_2', models.ImageField(blank=True, default='/static/1600x900.png', null=True, upload_to='about_images')),
                ('user_image_3', models.ImageField(blank=True, default='/static/1600x900.png', null=True, upload_to='about_images')),
                ('user_name_1', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name_2', models.CharField(blank=True, max_length=20, null=True)),
                ('user_name_3', models.CharField(blank=True, max_length=20, null=True)),
                ('user_occupation_1', models.CharField(blank=True, max_length=50, null=True)),
                ('user_occupation_2', models.CharField(blank=True, max_length=50, null=True)),
                ('user_occupation_3', models.CharField(blank=True, max_length=50, null=True)),
                ('user_social_media_1', models.CharField(blank=True, default='Facebook', max_length=20, null=True)),
                ('user_social_media_2', models.CharField(blank=True, default='Facebook', max_length=20, null=True)),
                ('user_social_media_3', models.CharField(blank=True, default='Facebook', max_length=20, null=True)),
                ('user_social_media_link_1', models.URLField(default='https://google.com')),
                ('user_social_media_link_2', models.URLField(default='https://google.com')),
                ('user_social_media_link_3', models.URLField(default='https://google.com')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.AlterModelOptions(
            name='pagecontents',
            options={'verbose_name': 'PageContent', 'verbose_name_plural': 'PageContents'},
        ),
    ]
