# Generated by Django 4.0.4 on 2023-01-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_about_alter_pagecontents_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='user_social_media_1',
            new_name='user_social_media_1_facebook',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='user_social_media_2',
            new_name='user_social_media_2_facebook',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='user_social_media_3',
            new_name='user_social_media_3_facebook',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='user_social_media_link_3',
            new_name='user_social_media_link_1_facebook',
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_1_instagram',
            field=models.CharField(blank=True, default='Instagram', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_1_twitter',
            field=models.CharField(blank=True, default='Twitter', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_2_insatgram',
            field=models.CharField(blank=True, default='Instagram', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_2_twitter',
            field=models.CharField(blank=True, default='Twitter', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_3_instagram',
            field=models.CharField(blank=True, default='Instagram', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_3_twitter',
            field=models.CharField(blank=True, default='Twitter', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_link_1_twitter',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_link_2_facebook',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_link_2_twitter',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_link_3_facebook',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_link_3_instagram',
            field=models.URLField(default='https://google.com'),
        ),
        migrations.AddField(
            model_name='about',
            name='user_social_media_link_3_twitter',
            field=models.URLField(default='https://google.com'),
        ),
    ]
