# Generated by Django 4.0.4 on 2023-01-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_user_social_media_1_about_user_social_media_1_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_1_facebook',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_1_instagram',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_1_twitter',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_2_facebook',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_2_insatgram',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_2_twitter',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_3_facebook',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_3_instagram',
        ),
        migrations.RemoveField(
            model_name='about',
            name='user_social_media_3_twitter',
        ),
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
